name: Deploy to NuGet

on:
  release:
    types: [published]

env:
  PROJECT_PATH: "Acl.Net/Acl.Net/Acl.Net.csproj"
  OUTPUT_PATH: ${{ github.workspace }}\output
  GITHUB_PATH: "https://github.com/vnedyalkov91/Acl.Net"

jobs:
  deploy:
    name: Deploy
    runs-on: windows-latest

    steps:
    # Checkout the repo
    - name: Checkout
      uses: actions/checkout@v2

    # Setup .Net version 3.1.x
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    # Build
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

    # Get Version
    - name: Get Version
      id: get_version
      uses: battila7/get-version-action@v2

    - name: Add Source
     run: dotnet nuget add source --username vnedyalkov91 --password ${{ secrets.GITHUBTOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/vnedyalkov91/index.json"

    # Package
    - name: Package
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.get_version.outputs.version-without-v }} --output ${{ env.OUTPUT_PATH }}

    # Push
    - name: Push
      run: dotnet nuget push ${{ env.OUTPUT_PATH }}\*.nupkg -k ${{ secrets.GITHUBDEPLOYERKEY }} --api-key ${{ env.GITHUB_PATH }} --source "github"
